### ISSUE TITLE
color text in preview tile for title

### ISSUE THREAD

**Issue by z0r0z** [kalidao/wrappr-ui#10]
this will highlight against description 
![image](https://user-images.githubusercontent.com/92001561/185560493-b906b6c3-b231-4674-9257-6f1371f64769.png)

**Comment by nerderlyne** [comment]
Not sure if colour change is the way. Maybe changing boldness or using a dimmer version of white for description? or positioning? @z0r0z

**Comment by z0r0z** [comment]
yeah maybe we just have outlined black text (so like hollow....)?
