### ISSUE TITLE
Automate document creation for LLC and UNA

### ISSUE THREAD

**Issue by nerderlyne** [kalidao/wrappr-ui#11]
- [x] Add Del LLC JS Template
- [x] Add Wyo LLC JS Template
- [x] Add UNA JS Template

**Comment by nerderlyne** [comment]
@z0r0z can you nit subseries for del and wyo?

**Comment by z0r0z** [comment]
following up here, I think we can start with just basing the mints on the baseURI default template and add some details as traits in uri as we sort through the doc generation for each tokenURI

**Comment by nerderlyne** [comment]
https://github.com/kalidao/wrappr-engine
