### ISSUE TITLE
llc name checks 

### ISSUE THREAD

**Issue by nerderlyne** [kalidao/wrappr-ui#18]
**delaware** 
- check for name collisions 
- formatting: `<Name> LLC`
https://delaware.gov/guides/data/

**wyoming** 
- formatting : `Wrappr LLC - <Name> - Series <TokenId>`
https://sos.wyo.gov/Forms/WyoBiz/Series_LLC_Rules.pdf

**Comment by nerderlyne** [comment]
@z0r0z is their anything else?

**Comment by z0r0z** [comment]
this looks good @nerderlyne I would also confirm that there is no collision within the Del or Wy Series Names, respectively

**Comment by nerderlyne** [comment]
I believe that's only necessary for Wy, checking within the State superset will take care of our subset as well
