### ISSUE TITLE
highlighted text in entity form

### ISSUE THREAD

**Issue by z0r0z** [kalidao/wrappr-ui#25]
It would be more legible that default inputs are placeholders (name, juris) if they are grey - and we should also do similar grey, underline or other highlighting of this text in the scrawl at bottom of form
![image](https://user-images.githubusercontent.com/92001561/187746176-d7101b64-5df3-43c5-986c-63d566ff1964.png)

**Comment by nerderlyne** [comment]
Those are not placeholders. Will be sorted in design improvement of mint form.
