### ISSUE TITLE
redesign minter flow

### ISSUE THREAD

**Issue by z0r0z** [kalidao/wrappr-ui#31]
we should character limit this too so it doesn't look weird

**Comment by nerderlyne** [comment]
- [ ] add template based form 
- [ ] integrate engine 

flow -> 
![image](https://user-images.githubusercontent.com/13903299/189477662-4bbf4007-fcde-4211-ac8e-82903c24fc2c.png)

**Comment by nerderlyne** [comment]
- [ ] add orange and lex
- [ ] add de llc api check
