### ISSUE TITLE
🐛 Error viewing individual entity NFT

### ISSUE THREAD

**Issue by audsssy** [kalidao/wrappr-ui#67]
**Describe the bug**
Link is broken when viewing a minted entity NFT

**To Reproduce**
1. Go to `user` in header
![Screenshot 2023-01-09 at 14 48 45](https://user-images.githubusercontent.com/5264156/211395120-93e3128c-fc5e-4962-a309-90fe71fe30de.png)
3. Click on `user`
4. Click on any NFT 
5. See error

**Expected behavior**
User should be able to view minted entity NFT

**Additional context**
Looks like issue is caused by highlighted line in screenshot below, as link is missing the proper Wrappr address between `chainId` and `id`.
![Screenshot 2023-01-09 at 14 50 17](https://user-images.githubusercontent.com/5264156/211395388-30df8a74-885a-435d-b396-ff119b29a286.png)

**Comment by nerderlyne** [comment]
[6e70004](https://github.com/kalidao/wrappr-ui/commit/6e700049a92fae5bcd7acc7a56bf1e1d3b61f0c4) should fix i think
